export default {
  FETCH_DATASET_REQUEST: "FETCH_DATASET_REQUEST",
  FETCH_DATASET_SUCCESS: "FETCH_DATASET_SUCCESS",
  FETCH_DATASET_FAILURE: "FETCH_DATASET_FAILURE",
  FETCH_GEOLOCATION_REQUEST: "FETCH_GEOLOCATION_REQUEST",
  FETCH_GEOLOCATION_SUCCESS: "FETCH_GEOLOCATION_SUCCESS",
  FETCH_GEOLOCATION_FAILURE: "FETCH_GEOLOCATION_FAILURE",
}
